name = "tenshipro"
main = ".svelte-kit/cloudflare/_worker.js"
preview_urls = false
workers_dev = false
compatibility_date = "2025-09-30"
compatibility_flags = [
	"nodejs_compat"
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = false

[build]
command = "yarn run build"

[vars]
NODE_VERSION = "22.20.0"

[[routes]]
pattern = "tenshipro.com"
custom_domain = true
